name: Update repo
on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
